/**
 * ビジネス価値と戦略質問モジュール
 *
 * クラウドネイティブ技術がビジネス価値と戦略に与える影響に関する質問を定義するモジュールです。
 * ROI測定、ビジネスアジリティ、デジタル変革などの側面を評価します。
 */

import { AssessmentQuestion } from "@shared/schema";

export const businessValueStrategyQuestions: AssessmentQuestion[] = [
  {
    id: "bvs_1",
    category: "business_value_strategy",
    text: {
      ja: "クラウドネイティブの取り組みによるビジネス価値をどのように測定していますか？",
      en: "How do you measure the business value generated by your cloud-native initiatives?",
    },
    weight: 1,
    maturityImportance: "high",
    roleRelevance: {
      executive: "high",
      manager: "medium",
      practitioner: "low",
    },
    assessmentType: "quick",
    baseQuestion: true,
    maturityLevel: "beginner",
    hasKnowledgeResource: true,
    knowledge: {
      ja: {
        summary:
          "クラウドネイティブの取り組みがビジネスに与える影響を測定することで、投資の正当化や継続的な最適化が可能になります。市場投入までの時間短縮、運用コスト削減、イノベーション能力向上などが一般的な価値指標です。",
        links: [
          {
            text: "Cloud Value Measurement",
            url: "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/clouds-trillion-dollar-prize-is-up-for-grabs",
          },
          {
            text: "Business Benefits of Cloud Native",
            url: "https://www.cncf.io/reports/cncf-annual-survey-2021/",
          },
        ],
      },
      en: {
        summary:
          "Measuring the impact of cloud-native initiatives on the business enables investment justification and continual optimization. Common indicators include shorter time-to-market, lower operating costs, and greater innovation capability.",
        links: [
          {
            text: "Cloud Value Measurement",
            url: "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/clouds-trillion-dollar-prize-is-up-for-grabs",
          },
          {
            text: "Business Benefits of Cloud Native",
            url: "https://www.cncf.io/reports/cncf-annual-survey-2021/",
          },
        ],
      },
    },
    options: [
      {
        value: 0,
        label: {
          ja: "クラウドネイティブの取り組みとビジネス価値の関連付けは行われておらず、主に技術的な指標のみで評価している",
          en: "No linkage between cloud-native initiatives and business value; evaluation relies mainly on technical metrics.",
        },
      },
      {
        value: 33,
        label: {
          ja: "コスト削減や基本的な効率化指標など、限定的なビジネス価値指標は測定しているが、包括的な価値測定フレームワークはない",
          en: "Limited business-value metrics (e.g., cost reduction, basic efficiency) are measured, but no comprehensive framework exists.",
        },
      },
      {
        value: 66,
        label: {
          ja: "市場投入までの時間短縮、顧客体験向上、収益への貢献など、主要なビジネス価値指標と紐づけたクラウドネイティブ評価フレームワークが確立されている",
          en: "A framework links key business-value metrics—time-to-market, customer experience, revenue impact—to cloud-native evaluation.",
        },
      },
      {
        value: 100,
        label: {
          ja: "包括的なビジネス価値測定フレームワークが実装され、クラウドネイティブ施策と具体的なビジネス成果の相関が常に測定・可視化され、投資判断に活用されている",
          en: "A comprehensive business-value framework continuously measures and visualizes correlations between cloud-native work and concrete business outcomes for investment decisions.",
        },
      },
      {
        value: -1,
        label: {
          ja: "わかりません",
          en: "I don't know",
        },
        isDontKnow: true,
        description: {
          ja: "このトピックについての知識がない場合は、このオプションを選択してください。",
          en: "Choose this option if you're not familiar with this topic.",
        },
      },
    ],
  },

  {
    id: "bvs_2",
    category: "business_value_strategy",
    text: {
      ja: "クラウドネイティブ戦略と全社的なデジタルトランスフォーメーション目標はどの程度整合していますか？",
      en: "To what extent is your cloud-native strategy aligned with company-wide digital-transformation goals?",
    },
    weight: 1,
    maturityImportance: "high",
    roleRelevance: {
      executive: "high",
      manager: "medium",
      practitioner: "none",
    },
    assessmentType: "quick",
    baseQuestion: true,
    maturityLevel: "beginner",
    hasKnowledgeResource: true,
    knowledge: {
      ja: {
        summary:
          "クラウドネイティブ戦略が全社的なデジタルトランスフォーメーション目標と整合していることで、取り組みの一貫性と効果が高まります。孤立した技術イニシアチブではなく、ビジネス全体の変革を支える要素として位置づけることが重要です。",
        links: [
          {
            text: "Digital Transformation Strategy",
            url: "https://www.mckinsey.com/business-functions/mckinsey-digital/our-insights/digital-strategy-in-a-time-of-crisis",
          },
          {
            text: "Cloud Native Transformation",
            url: "https://www.container-solutions.com/cloud-native-transformation",
          },
        ],
      },
      en: {
        summary:
          "Aligning the cloud-native strategy with enterprise-wide digital-transformation goals boosts consistency and effectiveness. The strategy should underpin overall business transformation rather than remain an isolated tech initiative.",
        links: [
          {
            text: "Digital Transformation Strategy",
            url: "https://www.mckinsey.com/business-functions/mckinsey-digital/our-insights/digital-strategy-in-a-time-of-crisis",
          },
          {
            text: "Cloud Native Transformation",
            url: "https://www.container-solutions.com/cloud-native-transformation",
          },
        ],
      },
    },
    options: [
      {
        value: 0,
        label: {
          ja: "クラウドネイティブ活動は主に技術部門の取り組みとして孤立しており、全社的なデジタル戦略との明確な連携がない",
          en: "Cloud-native activities are isolated within IT with no clear linkage to enterprise digital strategy.",
        },
      },
      {
        value: 33,
        label: {
          ja: "クラウドネイティブとデジタル戦略の間に基本的な整合性はあるが、具体的な目標や評価指標の統合は限定的",
          en: "Basic alignment exists, but specific goals and KPIs are not fully integrated.",
        },
      },
      {
        value: 66,
        label: {
          ja: "クラウドネイティブ戦略がデジタルトランスフォーメーション計画の重要な柱として位置づけられ、共通の指標と目標が設定されている",
          en: "The cloud-native strategy is a key pillar of the digital-transformation plan, with shared metrics and targets.",
        },
      },
      {
        value: 100,
        label: {
          ja: "クラウドネイティブとデジタル戦略が完全に統合され、ビジネス変革の中核として経営層に認識され、事業戦略の意思決定にも直接反映されている",
          en: "Cloud-native and digital strategies are fully integrated, recognized by executives as central to business transformation and reflected directly in corporate decisions.",
        },
      },
      {
        value: -1,
        label: {
          ja: "わかりません",
          en: "I don't know",
        },
        isDontKnow: true,
        description: {
          ja: "このトピックについての知識がない場合は、このオプションを選択してください。",
          en: "Choose this option if you're not familiar with this topic.",
        },
      },
    ],
  },

  {
    id: "bvs_3",
    category: "business_value_strategy",
    text: {
      ja: "クラウドネイティブへの移行を正当化するビジネスケースをどのように構築していますか？",
      en: "How do you construct the business case that justifies migrating to cloud-native?",
    },
    weight: 1,
    maturityImportance: "high",
    roleRelevance: {
      executive: "high",
      manager: "medium",
      practitioner: "low",
    },
    assessmentType: "quick",
    baseQuestion: true,
    maturityLevel: "beginner",
    hasKnowledgeResource: true,
    knowledge: {
      ja: {
        summary:
          "クラウドネイティブへの移行には、初期投資や組織変更が必要です。明確なビジネスケースを構築することで、投資の正当化、経営層の支持獲得、優先順位付けが可能になります。",
        links: [
          {
            text: "Cloud Business Case",
            url: "https://www.mckinsey.com/industries/financial-services/our-insights/next-gen-technology-transformation-in-financial-services",
          },
          {
            text: "Cloud ROI",
            url: "https://www.digitalocean.com/resources/articles/cloud-roi",
          },
        ],
      },
      en: {
        summary:
          "Moving to cloud-native requires upfront investment and organizational change. Building a clear business case justifies spending, secures executive buy-in, and sets priorities.",
        links: [
          {
            text: "Cloud Business Case",
            url: "https://www.mckinsey.com/industries/financial-services/our-insights/next-gen-technology-transformation-in-financial-services",
          },
          {
            text: "Cloud ROI",
            url: "https://www.digitalocean.com/resources/articles/cloud-roi",
          },
        ],
      },
    },
    options: [
      {
        value: 0,
        label: {
          ja: "明確なビジネスケースは構築されておらず、技術的な必要性や業界トレンドに基づいて判断されている",
          en: "No clear business case; decisions rely on technical necessity or industry trends.",
        },
      },
      {
        value: 33,
        label: {
          ja: "基本的なコスト分析とROI計算は行われているが、包括的なビジネスケースフレームワークはない",
          en: "Basic cost analysis and ROI calculations are performed, but no comprehensive framework exists.",
        },
      },
      {
        value: 66,
        label: {
          ja: "定量的および定性的なメリットを含む包括的なビジネスケースが構築され、投資判断や優先順位付けに活用されている",
          en: "A comprehensive business case—including quantitative and qualitative benefits—is built and used for investment decisions and prioritization.",
        },
      },
      {
        value: 100,
        label: {
          ja: "高度なビジネスケースフレームワークが確立され、詳細なTCO分析、リスク評価、機会コスト分析、長期的価値予測などが標準化され、継続的に更新されている",
          en: "An advanced framework is standardized with detailed TCO, risk, opportunity-cost, and long-term value forecasts, and it is continuously updated.",
        },
      },
      {
        value: -1,
        label: {
          ja: "わかりません",
          en: "I don't know",
        },
        isDontKnow: true,
        description: {
          ja: "このトピックについての知識がない場合は、このオプションを選択してください。",
          en: "Choose this option if you're not familiar with this topic.",
        },
      },
    ],
  },

  /* ───────────────── Adaptive Questions (shown based on dependencies) ───────────────── */
  {
    id: "bvs_4",
    category: "business_value_strategy",
    text: {
      ja: "クラウドネイティブ導入に関する主要パフォーマンス指標（KPI）をどのように定義し追跡していますか？",
      en: "How do you define and track key performance indicators (KPIs) for cloud-native adoption?",
    },
    weight: 1,
    maturityImportance: "high",
    roleRelevance: {
      executive: "high",
      manager: "high",
      practitioner: "medium",
    },
    assessmentType: "standard",
    dependencies: [{ questionId: "bvs_1", minValue: 33 }],
    maturityLevel: "intermediate",
    hasKnowledgeResource: true,
    knowledge: {
      ja: {
        summary:
          "クラウドネイティブ導入の成功を測定するためには、技術的・ビジネス的側面を含む明確なKPIを設定することが重要です。これにより、進捗状況の追跡、調整、成功の証明が可能になります。",
        links: [
          {
            text: "Cloud KPIs",
            url: "https://cloud.google.com/blog/products/management-tools/using-slis-slos-and-slas-to-measure-reliability",
          },
          {
            text: "DevOps Performance Measurement",
            url: "https://cloud.google.com/devops/state-of-devops/",
          },
        ],
      },
      en: {
        summary:
          "Clear KPIs—covering both technical and business aspects—are essential to track, adjust, and prove the success of cloud-native adoption.",
        links: [
          {
            text: "Cloud KPIs",
            url: "https://cloud.google.com/blog/products/management-tools/using-slis-slos-and-slas-to-measure-reliability",
          },
          {
            text: "DevOps Performance Measurement",
            url: "https://cloud.google.com/devops/state-of-devops/",
          },
        ],
      },
    },
    options: [
      {
        value: 0,
        label: {
          ja: "クラウドネイティブ導入に関する明確なKPIは定義されておらず、体系的な追跡も行われていない",
          en: "No clear KPIs defined; no systematic tracking.",
        },
      },
      {
        value: 33,
        label: {
          ja: "基本的な技術KPI（コンテナ化率、デプロイ頻度など）は定義されているが、ビジネス指標との連携や体系的な追跡は限定的",
          en: "Basic technical KPIs (containerization rate, deployment frequency, etc.) exist, but linkage to business metrics and systematic tracking are limited.",
        },
      },
      {
        value: 66,
        label: {
          ja: "技術的・ビジネス的側面を含む包括的なKPIフレームワークが定義され、定期的に追跡・報告されている",
          en: "A comprehensive KPI framework covering technical and business aspects is defined and regularly tracked and reported.",
        },
      },
      {
        value: 100,
        label: {
          ja: "高度なKPI管理システムが確立され、リアルタイムダッシュボード、予測分析、自動アラート、階層的スコアカードなどが実装され、継続的な最適化に活用されている",
          en: "An advanced KPI system with real-time dashboards, predictive analytics, auto-alerts, and hierarchical scorecards drives continuous optimization.",
        },
      },
      {
        value: -1,
        label: {
          ja: "わかりません",
          en: "I don't know",
        },
        isDontKnow: true,
        description: {
          ja: "このトピックについての知識がない場合は、このオプションを選択してください。",
          en: "Choose this option if you're not familiar with this topic.",
        },
      },
    ],
  },

  {
    id: "bvs_5",
    category: "business_value_strategy",
    text: {
      ja: "クラウドネイティブ技術の導入による競争優位性をどのように評価していますか？",
      en: "How do you evaluate the competitive advantage gained through cloud-native technologies?",
    },
    weight: 1,
    maturityImportance: "medium",
    roleRelevance: {
      executive: "high",
      manager: "medium",
      practitioner: "low",
    },
    assessmentType: "standard",
    dependencies: [{ questionId: "bvs_2", minValue: 33 }],
    maturityLevel: "intermediate",
    hasKnowledgeResource: true,
    knowledge: {
      ja: {
        summary:
          "クラウドネイティブ技術は、市場への迅速な対応、スケーラビリティ、イノベーション能力の向上など、多くの競争優位性をもたらす可能性があります。これらの優位性を明確に評価することで、戦略的な投資判断が可能になります。",
        links: [
          {
            text: "Cloud Competitive Advantage",
            url: "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/the-top-trends-in-tech",
          },
          {
            text: "Digital Business Strategy",
            url: "https://www.walkme.com/glossary/digital-business-strategy/",
          },
        ],
      },
      en: {
        summary:
          "Cloud-native technologies can create advantages such as faster market response, scalability, and improved innovation. Clear evaluation of these advantages supports strategic investment decisions.",
        links: [
          {
            text: "Cloud Competitive Advantage",
            url: "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/the-top-trends-in-tech",
          },
          {
            text: "Digital Business Strategy",
            url: "https://www.walkme.com/glossary/digital-business-strategy/",
          },
        ],
      },
    },
    options: [
      {
        value: 0,
        label: {
          ja: "クラウドネイティブ技術の競争優位性に関する体系的な評価は行われていない",
          en: "No systematic evaluation of competitive advantage from cloud-native technologies.",
        },
      },
      {
        value: 33,
        label: {
          ja: "基本的な競争優位性（市場投入時間の短縮など）は認識されているが、体系的な評価や定量化は限定的",
          en: "Basic advantages (e.g., faster time-to-market) are recognized, but systematic evaluation or quantification is limited.",
        },
      },
      {
        value: 66,
        label: {
          ja: "競争優位性の複数の側面（市場対応力、スケーラビリティ、イノベーション能力など）が評価され、戦略的意思決定に活用されている",
          en: "Multiple aspects—market responsiveness, scalability, innovation—are assessed and used in strategic decisions.",
        },
      },
      {
        value: 100,
        label: {
          ja: "高度な競争優位性評価フレームワークが確立され、定量的・定性的分析、業界ベンチマーク比較、市場動向分析などが統合され、継続的な戦略の最適化に活用されている",
          en: "An advanced framework integrates quantitative and qualitative analysis, industry benchmarks, and market-trend insights to optimize strategy continuously.",
        },
      },
      {
        value: -1,
        label: {
          ja: "わかりません",
          en: "I don't know",
        },
        isDontKnow: true,
        description: {
          ja: "このトピックについての知識がない場合は、このオプションを選択してください。",
          en: "Choose this option if you're not familiar with this topic.",
        },
      },
    ],
  },

  {
    id: "bvs_6",
    category: "business_value_strategy",
    text: {
      ja: "クラウドネイティブ投資のリターン（ROI）をどのように計算し、最適化していますか？",
      en: "How do you calculate and optimize the return on investment (ROI) of your cloud-native investments?",
    },
    weight: 1,
    maturityImportance: "high",
    roleRelevance: {
      executive: "high",
      manager: "medium",
      practitioner: "low",
    },
    assessmentType: "standard",
    dependencies: [{ questionId: "bvs_3", minValue: 33 }],
    maturityLevel: "intermediate",
    hasKnowledgeResource: true,
    knowledge: {
      ja: {
        summary:
          "クラウドネイティブ投資のROIを正確に計算することは、投資の正当化と最適化に不可欠です。これには、直接的なコスト削減だけでなく、市場投入時間の短縮、リスク軽減、新規収益機会など、多面的な要素を考慮する必要があります。",
        links: [
          {
            text: "Cloud ROI Calculation",
            url: "https://www.digitalocean.com/resources/articles/cloud-roi",
          },
          {
            text: "Cloud Investment Optimization",
            url: "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/clouds-trillion-dollar-prize-is-up-for-grabs",
          },
        ],
      },
      en: {
        summary:
          "Accurately calculating ROI is vital for justification and optimization. Beyond direct cost savings, consider time-to-market, risk reduction, and new-revenue opportunities.",
        links: [
          {
            text: "Cloud ROI Calculation",
            url: "https://www.digitalocean.com/resources/articles/cloud-roi",
          },
          {
            text: "Cloud Investment Optimization",
            url: "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/clouds-trillion-dollar-prize-is-up-for-grabs",
          },
        ],
      },
    },
    options: [
      {
        value: 0,
        label: {
          ja: "クラウドネイティブ投資のROIは体系的に計算されておらず、主に直感や技術的必要性に基づいて判断されている",
          en: "ROI is not systematically calculated; decisions rely on intuition or technical necessity.",
        },
      },
      {
        value: 33,
        label: {
          ja: "基本的なROI計算（コスト削減、効率化など）は行われているが、包括的な分析や継続的な最適化は限定的",
          en: "Basic ROI calculations (cost savings, efficiency) exist, but comprehensive analysis and ongoing optimization are limited.",
        },
      },
      {
        value: 66,
        label: {
          ja: "多面的なROIフレームワーク（コスト、時間、品質、リスク、新規収益など）が確立され、定期的に評価・最適化されている",
          en: "A multidimensional ROI framework (cost, time, quality, risk, new revenue) is established and regularly optimized.",
        },
      },
      {
        value: 100,
        label: {
          ja: "高度なROI最適化システムが確立され、詳細なTCO分析、シナリオモデリング、リアルタイム追跡、自動最適化推奨などが実装されている",
          en: "An advanced ROI system with detailed TCO, scenario modeling, real-time tracking, and auto-optimization is in place.",
        },
      },
      {
        value: -1,
        label: {
          ja: "わかりません",
          en: "I don't know",
        },
        isDontKnow: true,
        description: {
          ja: "このトピックについての知識がない場合は、このオプションを選択してください。",
          en: "Choose this option if you're not familiar with this topic.",
        },
      },
    ],
  },

  /* ───────────────── Advanced Questions (Comprehensive) ───────────────── */
  {
    id: "bvs_7",
    category: "business_value_strategy",
    text: {
      ja: "クラウドネイティブ戦略を市場や業界の変化にどのように適応させていますか？",
      en: "How do you adapt your cloud-native strategy to market and industry changes?",
    },
    weight: 1,
    maturityImportance: "medium",
    roleRelevance: {
      executive: "high",
      manager: "medium",
      practitioner: "low",
    },
    assessmentType: "comprehensive",
    dependencies: [{ questionId: "bvs_2", minValue: 66 }],
    maturityLevel: "advanced",
    hasKnowledgeResource: true,
    knowledge: {
      ja: {
        summary:
          "クラウド技術と市場環境は急速に変化しています。効果的なクラウドネイティブ戦略は静的なものではなく、新技術、競合動向、顧客期待の変化に応じて継続的に適応する必要があります。",
        links: [
          {
            text: "Adaptive Cloud Strategy",
            url: "https://www.digitalocean.com/resources/articles/cloud-roi",
          },
          {
            text: "Digital Market Trends",
            url: "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/the-top-trends-in-tech",
          },
        ],
      },
      en: {
        summary:
          "Cloud technology and market conditions change rapidly. An effective strategy must evolve continuously with new tech, competitive moves, and shifting customer expectations.",
        links: [
          {
            text: "Adaptive Cloud Strategy",
            url: "https://www.digitalocean.com/resources/articles/cloud-roi",
          },
          {
            text: "Digital Market Trends",
            url: "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/the-top-trends-in-tech",
          },
        ],
      },
    },
    options: [
      {
        value: 0,
        label: {
          ja: "クラウドネイティブ戦略は市場や業界の変化に応じて体系的に見直されることはほとんどない",
          en: "The strategy is rarely reviewed in response to market or industry changes.",
        },
      },
      {
        value: 33,
        label: {
          ja: "基本的な市場動向は監視されているが、クラウドネイティブ戦略の体系的な適応や更新は限定的",
          en: "Basic market trends are monitored, but systematic adaptation or updates are limited.",
        },
      },
      {
        value: 66,
        label: {
          ja: "定期的な市場分析と戦略レビューのプロセスが確立され、クラウドネイティブ戦略が定期的に更新されている",
          en: "Regular market analysis and strategy reviews are in place; the strategy is updated periodically.",
        },
      },
      {
        value: 100,
        label: {
          ja: "高度な適応型戦略管理システムが確立され、継続的な市場インテリジェンス、シナリオ計画、俊敏な戦略調整プロセスが実装されている",
          en: "An advanced adaptive-strategy system with continuous market intelligence, scenario planning, and agile adjustments is implemented.",
        },
      },
      {
        value: -1,
        label: {
          ja: "わかりません",
          en: "I don't know",
        },
        isDontKnow: true,
        description: {
          ja: "このトピックについての知識がない場合は、このオプションを選択してください。",
          en: "Choose this option if you're not familiar with this topic.",
        },
      },
    ],
  },

  {
    id: "bvs_8",
    category: "business_value_strategy",
    text: {
      ja: "クラウドネイティブ導入における機会損失（実現できなかった価値）をどのように評価していますか？",
      en: "How do you evaluate the opportunity cost (unrealized value) of cloud-native adoption?",
    },
    weight: 1,
    maturityImportance: "medium",
    roleRelevance: {
      executive: "high",
      manager: "medium",
      practitioner: "low",
    },
    assessmentType: "comprehensive",
    dependencies: [{ questionId: "bvs_1", minValue: 66 }],
    maturityLevel: "advanced",
    hasKnowledgeResource: true,
    knowledge: {
      ja: {
        summary:
          "クラウドネイティブの機会損失を評価することで、導入の遅延や部分的実装によって失われる潜在的価値を理解できます。これにより、優先順位付けと投資判断が向上します。",
        links: [
          {
            text: "Digital Opportunity Cost",
            url: "https://www.walkme.com/glossary/digital-business-strategy/",
          },
          {
            text: "Value of Agility",
            url: "https://www.mckinsey.com/capabilities/strategy-and-corporate-finance/our-insights/innovation-in-a-crisis-why-it-is-more-critical-than-ever",
          },
        ],
      },
      en: {
        summary:
          "Assessing opportunity cost helps quantify value lost through delays or partial implementations, improving prioritization and investment decisions.",
        links: [
          {
            text: "Digital Opportunity Cost",
            url: "https://www.walkme.com/glossary/digital-business-strategy/",
          },
          {
            text: "Value of Agility",
            url: "https://www.mckinsey.com/capabilities/strategy-and-corporate-finance/our-insights/innovation-in-a-crisis-why-it-is-more-critical-than-ever",
          },
        ],
      },
    },
    options: [
      {
        value: 0,
        label: {
          ja: "クラウドネイティブ導入における機会損失は体系的に評価されていない",
          en: "Opportunity cost is not systematically evaluated.",
        },
      },
      {
        value: 33,
        label: {
          ja: "基本的な機会損失の概念は認識されているが、体系的な評価や定量化は限定的",
          en: "The concept is recognized, but systematic evaluation or quantification is limited.",
        },
      },
      {
        value: 66,
        label: {
          ja: "機会損失の多面的評価フレームワークが確立され、先延ばしコスト、市場機会の喪失、競争上の不利などが分析されている",
          en: "A multifaceted framework analyzes postponement cost, lost market opportunities, competitive disadvantage, etc.",
        },
      },
      {
        value: 100,
        label: {
          ja: "高度な機会損失評価システムが確立され、詳細なシナリオモデリング、リアルオプション分析、時間価値計算などが実装され、投資判断に活用されている",
          en: "An advanced system with scenario modeling, real-options analysis, and time-value calculations informs investment decisions.",
        },
      },
      {
        value: -1,
        label: {
          ja: "わかりません",
          en: "I don't know",
        },
        isDontKnow: true,
        description: {
          ja: "このトピックについての知識がない場合は、このオプションを選択してください。",
          en: "Choose this option if you're not familiar with this topic.",
        },
      },
    ],
  },

  {
    id: "bvs_9",
    category: "business_value_strategy",
    text: {
      ja: "クラウドネイティブ導入の成功を評価するためのバランススコアカードをどのように設計・活用していますか？",
      en: "How do you design and use a balanced scorecard to evaluate cloud-native adoption success?",
    },
    weight: 1,
    maturityImportance: "medium",
    roleRelevance: {
      executive: "high",
      manager: "high",
      practitioner: "low",
    },
    assessmentType: "comprehensive",
    dependencies: [{ questionId: "bvs_4", minValue: 66 }],
    maturityLevel: "advanced",
    hasKnowledgeResource: true,
    knowledge: {
      ja: {
        summary:
          "バランススコアカードを採用することで、財務、顧客、内部プロセス、学習と成長の観点からクラウドネイティブ導入の多面的な成功を評価できます。",
        links: [
          {
            text: "IT Balanced Scorecard",
            url: "https://cio-wiki.org/wiki/IT_Balanced_Scorecard",
          },
          {
            text: "Strategic Performance Measurement",
            url: "https://hbr.org/2007/07/using-the-balanced-scorecard-as-a-strategic-management-system",
          },
        ],
      },
      en: {
        summary:
          "A balanced-scorecard approach evaluates success across financial, customer, internal-process, and learning & growth dimensions, ensuring balanced execution.",
        links: [
          {
            text: "IT Balanced Scorecard",
            url: "https://cio-wiki.org/wiki/IT_Balanced_Scorecard",
          },
          {
            text: "Strategic Performance Measurement",
            url: "https://hbr.org/2007/07/using-the-balanced-scorecard-as-a-strategic-management-system",
          },
        ],
      },
    },
    options: [
      {
        value: 0,
        label: {
          ja: "クラウドネイティブ導入のためのバランススコアカードは設計・活用されていない",
          en: "No balanced scorecard is designed or used.",
        },
      },
      {
        value: 33,
        label: {
          ja: "基本的な成功指標は定義されているが、多面的な評価やバランススコアカードのアプローチは採用されていない",
          en: "Basic success indicators exist, but no multifaceted balanced-scorecard approach.",
        },
      },
      {
        value: 66,
        label: {
          ja: "バランススコアカードが設計され、財務、顧客、内部プロセス、学習と成長の側面を含む評価が定期的に行われている",
          en: "A balanced scorecard covering financial, customer, internal-process, and learning & growth perspectives is used regularly.",
        },
      },
      {
        value: 100,
        label: {
          ja: "高度なバランススコアカードシステムが確立され、戦略マップ、階層指標、因果関係分析、予測モデリングなどが統合されている",
          en: "An advanced scorecard system integrates strategy maps, hierarchical metrics, causal analysis, and predictive modeling.",
        },
      },
      {
        value: -1,
        label: {
          ja: "わかりません",
          en: "I don't know",
        },
        isDontKnow: true,
        description: {
          ja: "このトピックについての知識がない場合は、このオプションを選択してください。",
          en: "Choose this option if you're not familiar with this topic.",
        },
      },
    ],
  },

  {
    id: "bvs_10",
    category: "business_value_strategy",
    text: {
      ja: "クラウドネイティブ戦略とイノベーション能力の向上をどのように関連付けていますか？",
      en: "How do you link your cloud-native strategy to improvements in innovation capability?",
    },
    weight: 1,
    maturityImportance: "high",
    roleRelevance: {
      executive: "high",
      manager: "medium",
      practitioner: "medium",
    },
    assessmentType: "comprehensive",
    dependencies: [{ questionId: "bvs_5", minValue: 66 }],
    maturityLevel: "advanced",
    hasKnowledgeResource: true,
    knowledge: {
      ja: {
        summary:
          "クラウドネイティブアプローチは、実験の容易化、市場フィードバックの迅速な取り込み、イノベーションサイクルの短縮など、組織のイノベーション能力を向上させる可能性があります。",
        links: [
          {
            text: "Cloud Innovation",
            url: "https://www.mckinsey.com/business-functions/mckinsey-digital/our-insights/innovating-from-necessity-the-business-building-imperative-in-the-current-crisis",
          },
          {
            text: "Digital Experimentation",
            url: "https://www.innosight.com/wp-content/uploads/2014/12/Innosight_HBR_Build-an-Innovation-Engine-in-90-Days.pdf",
          },
        ],
      },
      en: {
        summary:
          "Cloud-native approaches can boost innovation by easing experimentation, accelerating feedback loops, and shortening innovation cycles.",
        links: [
          {
            text: "Cloud Innovation",
            url: "https://www.mckinsey.com/business-functions/mckinsey-digital/our-insights/innovating-from-necessity-the-business-building-imperative-in-the-current-crisis",
          },
          {
            text: "Digital Experimentation",
            url: "https://www.innosight.com/wp-content/uploads/2014/12/Innosight_HBR_Build-an-Innovation-Engine-in-90-Days.pdf",
          },
        ],
      },
    },
    options: [
      {
        value: 0,
        label: {
          ja: "クラウドネイティブ戦略とイノベーション能力の向上の関連付けは体系的に行われていない",
          en: "No systematic linkage between cloud-native strategy and innovation capability.",
        },
      },
      {
        value: 33,
        label: {
          ja: "基本的な関連性は認識されているが、イノベーション能力の体系的な強化や測定は限定的",
          en: "Basic linkage is recognized, but systematic enhancement or measurement is limited.",
        },
      },
      {
        value: 66,
        label: {
          ja: "クラウドネイティブ戦略とイノベーション能力の関連付けが明確に行われ、実験文化の促進、イノベーションメトリクスの測定などが実施されている",
          en: "The linkage is clear; experimentation culture and innovation metrics are promoted and measured.",
        },
      },
      {
        value: 100,
        label: {
          ja: "高度なイノベーション戦略が確立され、クラウドネイティブ技術を活用した実験プラットフォーム、イノベーションパイプライン、価値創出測定システムなどが統合されている",
          en: "An advanced innovation strategy integrates experimentation platforms, innovation pipelines, and value-creation measurement systems leveraging cloud-native tech.",
        },
      },
      {
        value: -1,
        label: {
          ja: "わかりません",
          en: "I don't know",
        },
        isDontKnow: true,
        description: {
          ja: "このトピックについての知識がない場合は、このオプションを選択してください。",
          en: "Choose this option if you're not familiar with this topic.",
        },
      },
    ],
  },
];
